# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: uv-lock
        name: uv-lock
        entry: uv lock --check
        language: system
        pass_filenames: false
        always_run: true

      - id: black
        name: black
        entry: uv run --group lint black
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: uv run --group lint isort
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: uv run --group lint flake8
        pass_filenames: false
        language: system
        types: [python]
        args: ["src/"]

      - id: bandit
        name: bandit
        entry: uv run --group lint bandit
        language: system
        pass_filenames: false
        types: [python]
        args: ["-r", "src/"]
        exclude: ^tests/
